import { Poppins } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "./Providers";
import MyChakraProvider from "./ChakraProvider";

import { ReactQueryProvider } from "./ReactQueryProvider";


const inter = Poppins({ subsets: ["latin"],
weight:["100", "200", "300", "400", "500", "600", "700", "800", "900"] })

export const metadata = {
  title: "Resume Builder",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
  
      <body className={`${inter.className} main`}>
      
        <NextAuthProvider>
          <MyChakraProvider>
            <ReactQueryProvider>
            {children}

            </ReactQueryProvider>

          </MyChakraProvider>
       
        </NextAuthProvider>

        </body>
    </html>
  );
}
