import { Inter } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "./Providers";
import MyChakraProvider from "./ChakraProvider";
import Navbar from "./components/Navbar";
import { ReactQueryProvider } from "./ReactQueryProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Resume Builder",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
  
      <body className={`${inter.className} main`}>
      
        <NextAuthProvider>
          <MyChakraProvider>
            <ReactQueryProvider>
            {children}

            </ReactQueryProvider>
          
         

          </MyChakraProvider>
       
        </NextAuthProvider>

        </body>
    </html>
  );
}
